### ISSUE TITLE
建議，範例少用負面新聞

### ISSUE THREAD

**Issue by kyc1109** [virus-warnning/twnews#41]
建議，範例少用自殺等負面新聞，盡量傳遞正能量。

**Comment by virus-warnning** [comment]
會用負面新聞的原因是這樣的

這個專案是為了要改良凶宅爬蟲而設計，是鄉民風水師的副本
所以開發主軸會環繞著各種社會不幸事件進行最佳化，
因為目前台灣的人文地理應用過度強調正能量，太少人研究負能量，
以至於人們遇到負能量的狀況，沒有科技工具可以應用，
而透過數據分析，統計，神經網路等工具，可以幫助群眾改用科技趨吉避凶

以下兩個專案是目前正在嘗試的社會實驗，請參考
* https://geomancer.tacosync.com/#/mapviewer/14/25.04181/121.53424
* https://play.google.com/store/apps/details?id=tacoball.com.geomancer
