### ISSUE TITLE
I got a bug from your example

### ISSUE THREAD

**Issue by li195111** [virus-warnning/twnews#47]
I use the example - News Search and Break down.
Totally copy the code and got a bug.
Maybe you should fix it:)
my environ :
python 3.6.6
Windows 10

InvalidURL
Failed to parse: m.ltn.com.twD:\news\society\breakingnews\2581807

**Comment by virus-warnning** [comment]
Could you close this issue and create another issue with bug template?

**Comment by virus-warnning** [comment]
Cannot reproduce the problem. Close Issue.
